---
- name: Install Docker Pre-reqs
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: 
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - software-properties-common

- name: Add Docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Added Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic stable
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce 
    update_cache: yes

