---
- name: Create VPC
  ec2_vpc_net:
    state: present  
    name: "{{ air_app_name }}_vpc"
    aws_access_key: "{{ air_aws_access_key }}"
    aws_secret_key: "{{ air_aws_secret_key }}"
    cidr_block: "{{ air_vpc_cidr_start }}/16"
    region: "{{ air_aws_region }}"

- name: Lookup VPC details
  ec2_vpc_net_facts:
    aws_access_key: "{{ air_aws_access_key }}"
    aws_secret_key: "{{ air_aws_secret_key }}"
    region: "{{ air_aws_region }}"
    filters:
      "tag:Name":  "{{ air_app_name }}_vpc"
  register: vpc_lookup

- name: Capture VPC details
  set_fact:
    air_vpc: "{{ vpc_lookup.vpcs[0] }}"